In [2]:
# Step (1): Importing Libaries
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
# Step(2): Loading iris dataset
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
# Step(3): Dropping the "species" column
iris. drop(labels = 'species', axis = 1, inplace = True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [6]:
# Step(4) Adding columns
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  sepal_sum
0           5.1          3.5           1.4          0.2        8.6
1           4.9          3.0           1.4          0.2        7.9
2           4.7          3.2           1.3          0.2        7.9
3           4.6          3.1           1.5          0.2        7.7
4           5.0          3.6           1.4          0.2        8.6

In [8]:
# Step(5)

mean = [np.mean(iris['sepal_length']),
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['sepal_length']),
        np.mean(iris['sepal_width'])]

mean = list(iris.mean())

summary_dict = {'mean':mean}

summary_df = pd.DataFrame(data = summary_dict)

summary_df

       mean
0  5.843333
1  3.057333
2  3.758000
3  1.199333
4  8.900667

In [9]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width   sepal_sum
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    8.900667
std        0.828066     0.435866      1.765298     0.762238    0.889272
min        4.300000     2.000000      1.000000     0.100000    6.800000
25%        5.100000     2.800000      1.600000     0.300000    8.300000
50%        5.800000     3.000000      4.350000     1.300000    8.850000
75%        6.400000     3.300000      5.100000     1.800000    9.575000
max        7.900000     4.400000      6.900000     2.500000   11.700000